package io.phasetwo.keycloak.kms.keys.envelope;

import com.google.auto.service.AutoService;
import io.phasetwo.keycloak.kms.keys.AbstractKmsKeyProviderFactory;
import io.phasetwo.keycloak.kms.keys.KmsKeyType;
import java.security.KeyPair;
import java.security.cert.X509Certificate;
import java.util.List;
import lombok.extern.jbosslog.JBossLog;
import org.keycloak.common.util.CertificateUtils;
import org.keycloak.common.util.KeyUtils;
import org.keycloak.common.util.PemUtils;
import org.keycloak.component.ComponentModel;
import org.keycloak.component.ComponentValidationException;
import org.keycloak.crypto.Algorithm;
import org.keycloak.keys.Attributes;
import org.keycloak.keys.KeyProvider;
import org.keycloak.keys.KeyProviderFactory;
import org.keycloak.models.KeycloakSession;
import org.keycloak.models.RealmModel;
import org.keycloak.provider.ProviderConfigProperty;
import org.keycloak.provider.ProviderConfigurationBuilder;

/** {@code kms-rsa-generated} — the KMS-backed replacement for {@code rsa-generated}. */
@JBossLog
@AutoService(KeyProviderFactory.class)
public class KmsRsaKeyProviderFactory extends AbstractKmsKeyProviderFactory {

  public static final String ID = "kms-rsa-generated";
  public static final int DEFAULT_KEY_SIZE = 2048;

  @Override
  public String getId() {
    return ID;
  }

  @Override
  protected KmsKeyType keyType() {
    return KmsKeyType.RSA;
  }

  protected String defaultAlgorithm() {
    return Algorithm.RS256;
  }

  @Override
  public KeyProvider create(KeycloakSession session, ComponentModel model) {
    return new KmsRsaKeyProvider(session, model, keyType(), defaultAlgorithm());
  }

  @Override
  protected void generate(KeycloakSession session, RealmModel realm, ComponentModel model) {
    int size = model.get(Attributes.KEY_SIZE_KEY, DEFAULT_KEY_SIZE);
    if (size != 1024 && size != 2048 && size != 3072 && size != 4096) {
      throw new ComponentValidationException("RSA key size must be 1024, 2048, 3072 or 4096");
    }

    KeyPair keyPair = KeyUtils.generateRsaKeyPair(size);
    // Derive the kid exactly as stock does — the RFC 7638 thumbprint of the public key — so a key
    // generated here and the same key generated by stock Keycloak publish under the same kid. That
    // equivalence is what lets the migrator move a realm across without changing JWKS.
    String kid = KeyUtils.createKeyId(keyPair.getPublic());
    X509Certificate certificate =
        CertificateUtils.generateV1SelfSignedCertificate(keyPair, realm.getName());

    model.put(Attributes.KID_KEY, kid);
    model.put(Attributes.CERTIFICATE_KEY, PemUtils.encodeCertificate(certificate));

    byte[] pkcs8 = keyPair.getPrivate().getEncoded();
    try {
      seal(session, model, realm.getId(), kid, pkcs8);
    } finally {
      java.util.Arrays.fill(pkcs8, (byte) 0);
    }

    log.infof(
        "kms: generated a %d-bit %s key for realm %s (kid %s); the private half exists in this"
            + " database only as KMS ciphertext",
        size, keyType().contextValue(), realm.getName(), kid);
  }

  @Override
  public List<ProviderConfigProperty> getConfigProperties() {
    ProviderConfigurationBuilder b = ProviderConfigurationBuilder.create();
    commonProperties().forEach(b::property);
    return b.property(Attributes.ENABLED_PROPERTY)
        .property(Attributes.ACTIVE_PROPERTY)
        .property(Attributes.KEY_SIZE_PROPERTY.get())
        .property(algorithmProperty())
        .build();
  }

  protected ProviderConfigProperty algorithmProperty() {
    return Attributes.RS_ALGORITHM_PROPERTY;
  }

  @Override
  public String getHelpText() {
    return "RSA keys generated in memory and stored encrypted under a cloud KMS key. The database"
        + " holds ciphertext; signing happens in this process at memory speed.";
  }
}
