"""Emit SigV4 reference vectors using botocore. See regenerate-sigv4-vectors.sh."""
import datetime
import json
import os

from botocore.auth import SigV4Auth
from botocore.awsrequest import AWSRequest
from botocore.credentials import Credentials


def vector(name, region, host, target, payload, creds):
    req = AWSRequest(method="POST", url=f"https://{host}/", data=payload)
    req.headers["Content-Type"] = "application/x-amz-json-1.1"
    req.headers["X-Amz-Target"] = target
    SigV4Auth(creds, "kms", region).add_auth(req)
    return {
        "name": name,
        "region": region,
        "host": host,
        "target": target,
        "payload": payload,
        "accessKeyId": creds.access_key,
        "secretAccessKey": creds.secret_key,
        "sessionToken": creds.token or "",
        "amzDate": req.headers["X-Amz-Date"],
        "authorization": req.headers["Authorization"],
    }


STATIC = Credentials("AKIDEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY")
TEMP = Credentials(
    "ASIAEXAMPLE", "wJalrXUtnFEMI/K7MDENG+bPxRfiCYEXAMPLEKEY", "FwoGZXIvYXdzEXAMPLETOKEN=="
)

VECTORS = [
    vector("encrypt-static", "us-east-1", "kms.us-east-1.amazonaws.com", "TrentService.Encrypt",
           '{"KeyId":"alias/keycloak-realm-keys","Plaintext":"AQID","EncryptionContext":{"app":"keycloak"}}',
           STATIC),
    vector("decrypt-session-token", "eu-west-1", "kms.eu-west-1.amazonaws.com", "TrentService.Decrypt",
           '{"CiphertextBlob":"AQICAHg="}', TEMP),
    vector("empty-payload", "us-west-2", "kms.us-west-2.amazonaws.com", "TrentService.DescribeKey",
           '{}', STATIC),
    vector("non-ascii-payload", "ap-southeast-2", "kms.ap-southeast-2.amazonaws.com", "TrentService.Sign",
           '{"KeyId":"arn:aws:kms:ap-southeast-2:111122223333:key/abc","Message":"3q2+7w==",'
           '"MessageType":"DIGEST","SigningAlgorithm":"ECDSA_SHA_256","Note":"café"}', STATIC),
]

DOC = {
    "_provenance": (
        "Generated by botocore (bundled with the AWS CLI) via botocore.auth.SigV4Auth, an "
        "implementation independent of this repository. Regenerate with "
        "src/test/resources/regenerate-sigv4-vectors.sh. These are the reference this project's "
        "AwsSigV4Signer is checked against; do not hand-edit a signature."
    ),
    "vectors": VECTORS,
}

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "sigv4-vectors.json")
with open(out, "w", encoding="utf-8") as fh:
    json.dump(DOC, fh, indent=2, ensure_ascii=False)
    fh.write("\n")
print(f"wrote {len(VECTORS)} vectors to {out}")
